---
- name: Copy Varnish default VCL.
  template:
    src: "{{ varnish_default_vcl_template_path }}"
    dest: "{{ varnish_config_path }}/default.vcl"
    owner: root
    group: root
    mode: 0644
  notify: restart varnish

# Workaround for systems where sysv and systemd script files
# https://github.com/ansible/ansible-modules-core/issues/3764
- name: Ensure Varnish services start on boot.
  command: systemctl enable -f {{ item }}
  with_items: "{{ varnish_enabled_services | default([]) }}"
  when: varnish_enabled_services and ansible_distribution_release == "jessie"
