---
- name: Copy Varnish default VCL.
  template:
    src: "{{ varnish_default_vcl_template_path }}"
    dest: "{{ varnish_config_path }}/default.vcl"
    owner: root
    group: root
    mode: 0644
  notify: restart varnish

# https://github.com/geerlingguy/ansible-role-varnish/pull/28
- name: Correct varnish.service permissions
  file:
    path: "{{ varnish_systemd_config_path }}/varnish.service"
    owner: root
    group: root
    mode: 0644
  when: >
    (ansible_os_family == 'Debian') and
    (ansible_distribution_release == "jessie" or ansible_distribution_release == "xenial")
